version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  pre_build:
    commands:
      - echo Iniciando build em `date`
      - mvn clean
  build:
    commands:
      - echo Build iniciado em `date`
      - mvn package
  post_build:
    commands:
      - echo Build completo em `date`

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - target/*.jar
    - pom.xml
    - src/**/*
  discard-paths: no
